### Get All Thread
GET http://localhost:8000/api/v1/thread
Content-Type: application/json

### Get Thread By Id
GET http://localhost:8000/api/v1/thread/6714751f80e1525131a2a4ce
Content-Type: application/json

### Add Thread
POST http://localhost:8000/api/v1/thread
Content-Type: application/json

{
   "title":"Test1",
   "content":"Apa itu test?",
   "categoryId":"67146f6d4c5fc86f3d4490be" 
}

### Update Thread
PATCH  http://localhost:8000/api/v1/thread
Content-Type: application/json

{
    "id": "6714751f80e1525131a2a4ce",
    "name":"Test"
}

### Delete Thread
DELETE  http://localhost:8000/api/v1/thread
Content-Type: application/json

{
    "id":"671452a281f5b18c196c2456"
}